core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, request_study, request_participant, delete_by_studyname, delete_by_session,\
    toggle_data_permission, delete_user, update_session_extract, request_session

app_name = "core"

urlpatterns = [
    path('extract_study/<str:study_name>/', request_study, name="extract_study"),
    path('extract_participant/<str:participant_name>/', request_participant, name="extract_participant"),
    path('extract_session/<str:sessionID>/',request_session, name="extract_session"),
    path('delete_by_studyname/<str:studyname>/', delete_by_studyname, name="delete_by_studyname"),
    path('delete_by_session/<str:sessionid>/', delete_by_session, name="delete_by_session"),
    path('toogle_data_usage_permission/', toggle_data_permission, name="toggle_data_permission"),
    path('update_session_extract/<str:studyname>/<str:participant_name>/', update_session_extract, name="update_session_extract"),
    path('delete_user/', delete_user, name="delete_user"),
    path('', index, name='index'),
]

esm/urls.py
# For URL and Routing
from django.contrib import admin
from django.urls import path, include
import signal
# For channels_presence
from channels_presence.models import Room, Presence
# For authentification
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

app_name = "esm"


urlpatterns = [
    path('acra/', include("acra.urls")),
    path('admin/', admin.site.urls, name='admin_page'),
    path('socket/', include('sessionhandler.urls')),
    path('', include('core.urls')),
    path('', include('authentification.urls')),
    path('', include('restframework.urls'))
]

# This code runs one time if you start the Server by command python3 manage.py runserver
from sessionhandler.scheduler import start
start()

templates/websocket/create_room.html
{% extends 'layouts/base.html' %}
{% block title %} Websocket Room Creation {% endblock title %}

{% block stylesheet %}
    <style>

        body{
            background-color: #444444;
        }

        #room-name-input{
            width: 90%;
            margin-bottom: 5px;
        }

        #top-element{
            margin-top: 35px;
            margin-bottom: 0px;
        }

        h2 {
            color: white;
            font-weight: bold;
        }
    </style>

{% endblock stylesheet %}


{% block content %}

    <div id="top-element" class="row">

        <div class="col">

            <div class="row justify-content-start">
                <div class="col">
                    <h2>Websocket Creation</h2>
                    <hr style="border-top: 1px solid white; margin-bottom: 35px;">
                </div>
            </div>

            <div class="row justify-content-center">

                <div class="card animated fadeInUp">
                    <div class="card-body">
                            <h5 class="card-title">Create a websocket space by typing in an identifier name:</h5>
                            <input id="room-name-input" type="text" size="100"><br>
                            <input id="room-name-submit" type="button" value="Open Connection">
                    </div>
                    <div class="card-footer">

                        <a href="{% url 'core:index' %}" style="float: right">Index Page</a>

                    </div>
                </div>

            </div>


        </div>






    </div>

{% endblock content %}


{% block javascript %}
    <script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;

        if(roomName === "" || roomName === "default"){
            alert("Type in an identifier to proceed. \n 'default' is not accepted.");
        } else {
            window.location.pathname = '/socket/' + roomName + '/';
        }

    }


    </script>
{% endblock javascript %}

templates/websocket/view_room.html
{% extends 'layouts/base.html' %}
{% block title %} Websocket Room{% endblock title %}

{% block stylesheet %}
    <style>

        body {
            background-color: #444444;
        }

        #top-element{
        margin-top: 35px;
        margin-bottom: 0px;
        }

        #chat-log{
            width: 90%;
            height: 500px;
            resize: none;
            overflow-y: scroll;
            border-style: solid;
            border-width: thin;
            margin-bottom: 5px;
            font-size: small;
        }

        #chat-message-input{
            width: 90%;
            margin-bottom: 5px;
        }

        h2 {
            color: white;
            font-weight: bold;
        }

    </style>

{% endblock stylesheet %}


{% block content %}

    <div id="top-element" class="row">
        <div class="col">

            <div class="row justify-content-start">
                <div class="col">
                    <h2>Websocket </h2>
                    <hr style="border-top: 1px solid white; margin-bottom: 35px;">
                </div>
            </div>

            <div class="row justify-content-center">

                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Your currently in Websocket with the identifier: </h5>
                            <h6 class="card-subtitle mb-2" style="color: green;">{{ room_name }}</h6>

                            <div id="chat-log" contenteditable="false">

                            </div>


                            <input id="chat-message-input" type="text" size="100"><br>
                            <input id="chat-message-submit" type="button" value="Send">
                            {{ room_name|json_script:"room-name" }}
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'core:index' %}" style="float: right">To Index-Page</a>
                        </div>
                    </div>
                </div>

            </div>


        </div>



    </div>

{% endblock content %}


{% block javascript %}
    <script>

        const roomName = JSON.parse(document.getElementById('room-name').textContent);


        var ws_scheme = window.location.protocol == 'https:' ? 'wss://' : 'ws://';
        const chatSocket = new WebSocket(
            ws_scheme
            + window.location.host
            + '/ws/socket/'
            + roomName
            + '/',
            'session-observation'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data + '\n');
            var div = document.getElementById('chat-log');
            div.innerHTML += "<pre>" + JSON.stringify(data, undefined, 2) + "</pre>";
            div.innerHTML += "<hr>";
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
            var div = document.getElementById('chat-log');
            div.innerHTML += "<span style='color:red'> Chat socket closed unexpectedly </span> <br> <hr>";
        }

        setInterval( function(){
            chatSocket.send(JSON.stringify({"heartbeat" : 1}))
        },10000)

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };


    </script>
{% endblock javascript %}