authentification/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import TokenRefreshView # new

app_name = "authentification"

urlpatterns = [
    # http://host/..URLS
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path('logout/', logout_user, name="logout"),

    # API
    path('api/sign_up/', APISignUpView.as_view(), name='sign_up'),
    path('api/log_in/', APILogInView.as_view(), name='log_in'),  # new
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  # new


    # Rest-API ~ Testing
    path('helloworld/', HelloView.as_view(), name="hello"),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth')
]

esm/urls.py
# For URL and Routing
from django.contrib import admin
from django.urls import path, include
import signal
# For channels_presence
from channels_presence.models import Room, Presence
# For authentification
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

app_name = "esm"


urlpatterns = [
    path('acra/', include("acra.urls")),
    path('admin/', admin.site.urls, name='admin_page'),
    path('socket/', include('sessionhandler.urls')),
    path('', include('core.urls')),
    path('', include('authentification.urls')),
    path('', include('restframework.urls'))
]

# This code runs one time if you start the Server by command python3 manage.py runserver
from sessionhandler.scheduler import start
start()

authentification/models.py
from django.db import models

# Create your models here.

authentification/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ),
        initial="")
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",
                "class": "form-control"
            }
        ),
        initial="")

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Re-type password",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

authentification/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.forms.utils import ErrorList
from django.http import HttpResponse
from .forms import LoginForm, SignUpForm
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth import get_user_model
from rest_framework import generics
from rest_framework_simplejwt.views import TokenObtainPairView  # new
from .serializers import LogInSerializer, UserSerializer  # changed


# Create your views here.
def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None
    submitted_once = False

    if request.method == "POST":
        submitted_once = True
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                msg = 'Ungültige Anmeldedaten'
        else:
            msg = 'Error validating the form'

    return render(request, "authentification/login.html",
                  {"form": form, "msg": msg, "submitted_already": submitted_once, })


def register_user(request):
    msg = None
    success = False
    submitted_once = False
    if request.method == "POST":
        submitted_once = True
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            msg = 'User created.'
            success = True
            # return redirect("/login/")
        else:
            msg = '  '
    else:
        form = SignUpForm()

    return render(request, "authentification/register.html",
                  {"form": form, "msg": msg, "success": success, "submitted_already": submitted_once, })


def logout_user(request):
    logout(request)
    return login_view(request)


class HelloView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        content = {'message': "Hello World!"}
        return Response(content)


class APISignUpView(generics.CreateAPIView):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer


class APILogInView(TokenObtainPairView):
    serializer_class = LogInSerializer

templates/authentification/login.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %} THRIlLEr ESM Login {% endblock %}

{% block stylesheet %}
    <style>
         html, body{
             background-color: #444444;
             height: 100%;
             min-height: 100%;
         }

         .row{
             height: 100%;
         }

         input{
             margin-top: 20px;
         }
    </style>
{% endblock stylesheet %}

{% block content %}


    {% if msg %}
        <div class="row" >
            <div class="col-md-4 align-self-center" style="padding-left: 80px;">

                <div class="card animated fadeInLeft">
                    <h5 class="card-header">Error Messages</h5>
                    <div class="card-body text-center" style="margin-bottom: -20px">

                        <p class="text-danger"> {{ msg }}</p>

                    </div>

                </div>

            </div>

    {% else %}
        <div class="row justify-content-center">
    {% endif %}

        <div class="col-md-4 align-self-center"  >
            {% if not submitted_already %}
            <div class="card animated fadeInDown">
            {% else %}
            <div class="card">
            {% endif %}
                <h5 class="card-header">Login - ESM </h5>
                <div class="card-body text-center">
                    <form role="form" method="post" action="">
                        {% csrf_token %}
                        {{ form.username }}
                        {{ form.password }}
                        <input type="submit" class="btn btn-primary" value="Log In" style="margin-top: 20px;">
                    </form>

                </div>
                <div class="card-footer">
                    <a href="{% url 'authentification:register' %}" style="margin-top: 20px;">Create New Account </a>
                </div>
            </div>

        </div>
    </div>




{% endblock content %}

templates/authentification/register.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %} Login - ESM {% endblock %}

{% block stylesheet %}
    <style>
         html, body{
             background-color: #444444;
             height: 100%;
             min-height: 100%;
         }

         .row{
             height: 100%;
         }

    </style>
{% endblock stylesheet %}

{% block content %}


    {% if msg %}
        <div class="row" >
            <div class="col-md-4 align-self-center" style="padding-left: 80px;">

                <div class="card animated fadeInLeft">
                    <h5 class="card-header">Messages</h5>
                    <div class="card-body">

                        <p class="text-danger text-center">
                            {{ msg }}
                        </p>

                        <p class="text-danger">
                            {{ form.username.errors }}
                            {{ form.email.errors }}
                            {{ form.password1.errors }}
                            {{ form.password2.errors }}
                        </p>

                    </div>

                </div>

            </div>

    {% else %}
        <div class="row justify-content-center full-height" style="height: 100%;" >
    {% endif %}

        <div class="col-md-4 align-self-center"  >
            {% if not submitted_already %}
            <div class="card animated fadeInRight">
            {% else %}
            <div class="card">
            {% endif %}
                <h5 class="card-header">Registration - ESM </h5>
                    {% if success %}

                    {% else %}
                        <div class="card-body text-center">
                            <form role="form" method="post" action="">
                                {% csrf_token %}
                                {{ form.username }}<br>
                                {{ form.email }}<br>
                                {{ form.password1 }}<br>
                                {{ form.password2 }}<br>
                                <input type="submit" class="btn btn-fill btn-primary" value="Register" style="margin-top: 20px;">
                            </form>

                        </div>
                    {% endif %}

                <div class="card-footer">
                    <a href="{% url 'authentification:login' %}" style="margin-top: 20px;">Zur Authentifizierung</a>
                </div>
            </div>

        </div>
    </div>




{% endblock content %}